# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            WunderWay
tagline:          The WunderRoot Intranet
description:      How we run our company and deliver projects
url:              http://wunderroot.co.uk

author:
  name:           WunderRoot
  url:            https://twitter.com/wunderroot

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/wunderroot/wunderway
  branch:         https://github.com/wunderroot/wunderway/tree/gh-pages
